In [1]:
!pip install tensorflow pandas numpy scikit-learn matplotlib seaborn nltk streamlit

Requirement already satisfied: tensorflow in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (2.21.0)
Requirement already satisfied: pandas in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (2.2.6)
Requirement already satisfied: scikit-learn in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: nltk in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (3.9.4)
Requirement already satisfied: streamlit in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (1.57.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.33.1)
Requirement already satisfied: setuptools in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (7.1.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: pyarrow>=7.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: starlette>=0.40.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (0.0.27)
Requirement already satisfied: websockets>=12.0.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: colorama in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: rich in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: h11>=0.8 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\vara prasad\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import pickle
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt

In [3]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\VARA
[nltk_data]     PRASAD\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\VARA
[nltk_data]     PRASAD\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [5]:
df = pd.read_csv("dataset/augmented_chatbot_dataset.csv")

df.head()

,Question,Answer
0,What subject is scheduled on Monday at 9:40 AM...,Open Elective – III
1,What class is at 10:40 AM on Monday for Sectio...,Integrated Circuits and Applications Lab (A1) ...
2,What subject is taught at 11:40 AM on Monday f...,Mini Project – II
3,What period is after lunch on Monday for Secti...,Microprocessors and Microcontrollers (MPMC)
4,What subject is from 2:20 PM to 3:20 PM on Mon...,Extra-Curricular Activities – II

In [6]:
df.dropna(inplace=True)

df.drop_duplicates(inplace=True)

df.columns = ['question', 'answer']

print(df.shape)

(4563, 2)

In [7]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    words = text.split()

    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

df['question'] = df['question'].apply(clean_text)

df.head()

[nltk_data] Downloading package stopwords to C:\Users\VARA
[nltk_data]     PRASAD\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\VARA
[nltk_data]     PRASAD\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,question,answer
0,subject scheduled monday 940 section,Open Elective – III
1,class 1040 monday section,Integrated Circuits and Applications Lab (A1) ...
2,subject taught 1140 monday section,Mini Project – II
3,period lunch monday section,Microprocessors and Microcontrollers (MPMC)
4,subject 220 pm 320 pm monday section,Extra-Curricular Activities – II

In [8]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['label'] = label_encoder.fit_transform(df['answer'])

df.head()

,question,answer,label
0,subject scheduled monday 940 section,Open Elective – III,291
1,class 1040 monday section,Integrated Circuits and Applications Lab (A1) ...,232
2,subject taught 1140 monday section,Mini Project – II,268
3,period lunch monday section,Microprocessors and Microcontrollers (MPMC),267
4,subject 220 pm 320 pm monday section,Extra-Curricular Activities – II,206

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(

    num_words=10000,

    oov_token="<OOV>"
)

tokenizer.fit_on_texts(df['question'])

X = tokenizer.texts_to_sequences(df['question'])

X = pad_sequences(

    X,

    maxlen=20,

    padding='post'
)

y = df['label']

print(X[0])

print(y[0])

[28 56 35 43  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
291

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42
)

print("Training samples:", len(X_train))

print("Testing samples:", len(X_test))

Training samples: 3650
Testing samples: 913

In [11]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Embedding,
    Conv1D,
    GlobalMaxPooling1D,
    Dense,
    Dropout
)

model = Sequential([

    Embedding(

        input_dim=10000,

        output_dim=64
    ),

    Conv1D(

        filters=64,

        kernel_size=3,

        activation='relu'
    ),

    GlobalMaxPooling1D(),

    Dense(

        64,

        activation='relu'
    ),

    Dropout(0.3),

    Dense(

        len(label_encoder.classes_),

        activation='softmax'
    )
])

model.compile(

    loss='sparse_categorical_crossentropy',

    optimizer='adam',

    metrics=['accuracy']
)

model.build(input_shape=(None, X_train.shape[1]))

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 20, 64)              │         640,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d (Conv1D)                      │ (None, 18, 64)              │          12,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling1d                 │ (None, 64)                  │               0 │
│ (GlobalMaxPooling1D)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 384)                 │          24,960 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 681,472 (2.60 MB)

 Trainable params: 681,472 (2.60 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=5,

    restore_best_weights=True
)

history = model.fit(

    X_train,
    y_train,

    epochs=40,

    batch_size=16,

    validation_data=(X_test, y_test),

    callbacks=[early_stop],

    verbose=1
)

Epoch 1/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 8s 18ms/step - accuracy: 0.0268 - loss: 5.5837 - val_accuracy: 0.0537 - val_loss: 5.0105
Epoch 2/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.1249 - loss: 4.3370 - val_accuracy: 0.2782 - val_loss: 3.6245
Epoch 3/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.3871 - loss: 2.7016 - val_accuracy: 0.6396 - val_loss: 1.8306
Epoch 4/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.6827 - loss: 1.3247 - val_accuracy: 0.9036 - val_loss: 0.7236
Epoch 5/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.8362 - loss: 0.6860 - val_accuracy: 0.9770 - val_loss: 0.2704
Epoch 6/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.9060 - loss: 0.4045 - val_accuracy: 0.9869 - val_loss: 0.1209
Epoch 7/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9345 - loss: 0.2552 - val_accuracy: 0.9945 - val_loss: 0.0633
Epoch 8/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - accuracy: 0.9608 - loss: 0.1795 - val_accuracy: 0.9978 - val_loss: 0.0407
Epoch 9/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - accuracy: 0.9668 - loss: 0.1436 - val_accuracy: 0.9956 - val_loss: 0.0286
Epoch 10/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9751 - loss: 0.1161 - val_accuracy: 0.9978 - val_loss: 0.0180
Epoch 11/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9784 - loss: 0.0882 - val_accuracy: 0.9978 - val_loss: 0.0166
Epoch 12/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9874 - loss: 0.0636 - val_accuracy: 0.9978 - val_loss: 0.0115
Epoch 13/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9844 - loss: 0.0666 - val_accuracy: 0.9989 - val_loss: 0.0106
Epoch 14/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9890 - loss: 0.0540 - val_accuracy: 0.9989 - val_loss: 0.0078
Epoch 15/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9871 - loss: 0.0476 - val_accuracy: 0.9989 - val_loss: 0.0062
Epoch 16/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - accuracy: 0.9890 - loss: 0.0427 - val_accuracy: 0.9989 - val_loss: 0.0066
Epoch 17/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - accuracy: 0.9910 - loss: 0.0423 - val_accuracy: 0.9989 - val_loss: 0.0047
Epoch 18/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9923 - loss: 0.0355 - val_accuracy: 0.9978 - val_loss: 0.0088
Epoch 19/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9923 - loss: 0.0323 - val_accuracy: 0.9989 - val_loss: 0.0077
Epoch 20/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.9918 - loss: 0.0350 - val_accuracy: 0.9989 - val_loss: 0.0044
Epoch 21/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.9926 - loss: 0.0321 - val_accuracy: 0.9978 - val_loss: 0.0044
Epoch 22/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9918 - loss: 0.0281 - val_accuracy: 0.9978 - val_loss: 0.0072
Epoch 23/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9942 - loss: 0.0232 - val_accuracy: 0.9978 - val_loss: 0.0097
Epoch 24/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.9940 - loss: 0.0265 - val_accuracy: 0.9978 - val_loss: 0.0119
Epoch 25/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9942 - loss: 0.0251 - val_accuracy: 0.9989 - val_loss: 0.0022
Epoch 26/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9934 - loss: 0.0237 - val_accuracy: 0.9989 - val_loss: 0.0029
Epoch 27/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9948 - loss: 0.0197 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 28/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9926 - loss: 0.0256 - val_accuracy: 1.0000 - val_loss: 0.0038
Epoch 29/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9940 - loss: 0.0211 - val_accuracy: 0.9978 - val_loss: 0.0038
Epoch 30/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.9934 - loss: 0.0209 - val_accuracy: 0.9978 - val_loss: 0.0044
Epoch 31/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9970 - loss: 0.0131 - val_accuracy: 0.9978 - val_loss: 0.0041
Epoch 32/40
229/229 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9967 - loss: 0.0144 - val_accuracy: 1.0000 - val_loss: 0.0018

In [13]:
import pickle

# Save model
model.save("chatbot_model.keras")

# Save tokenizer
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

# Save label encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

print("Model and files saved successfully")

Model and files saved successfully